---
name: Python Base Image
version: dev
slug: base-python
description: Docker Python base images used by Home Assistant Community Apps.
url: https://github.com/erik73/app-base-python
arch:
  - aarch64
  - amd64
